tasks:
  - init: docker compose build
    command: docker compose up -d
  - init: cargo install sqlx-cli
    command: cargo sqlx prepare --workspace
  - init: cargo build
    command: |
      gp ports await 5432
      cargo run
  - init: pnpm i
    command: |
      gp ports await 8080
      pnpm dev

ports:
  - name: Postgres DB
    description: The postgres database
    port: 5432
    onOpen: notify
  - name: Api
    description: The api server
    port: 8080
    onOpen: notify
  - name: Web App
    description: The main application web server
    port: 3000
    onOpen: open-browser
